language: node_js
node_js:
- '4'
- '6'
env:
  matrix:
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
before_install:
- npm install mitm
install: npm install
script: npm test
after_success:
- npm run coverage
